repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=4000']
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ['--line-length', '150']
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
