# c.f. https://arxiv.org/pdf/2102.12923
defaults:
  - default_algorithm
  - override dataloader: default_dataloader
  - normalizer: no_normalizer
  - override architecture: unet
  - _self_

name: image_baseline

dataloader:
  batch_size: 8

prediction_transform:
  inverse_transform_in_loss: False
  predict_residual: False
  name: softplus

sizing_field_interpolation_type: pixel  # Must be "pixel", since we act on pixels for all image-based methods.
image_resolution: 512  # The resolution of the image in the *longest* direction of the domain