defaults:
  - default_task
  - fem: poisson
  - domain: lshape
  - refinement_heuristic: theta_heuristic
  - _self_


name: poisson

num_data_points:
  train: 20  # number of data points to train on
  val: 20
  test: 20
max_initial_element_volume: 0.001
