fixed_target: False

# gmm parameters
density_mode: density  # either "density" or "log_density"
num_components: 3  # number of GMM components
distance_threshold: 0.01  # minimum distance between the means of the GMM components and the boundary
mean_position_range: ???  # maximum deviation range of the gmm mean from (0.5, 0.5)
lower_covariance_bound: ???  # minimum value of the isotropic covariance matrix
upper_covariance_bound: ???  # maximum value of the isotropic covariance matrix
