# @package _global_

defaults:
  - _amber
  - override /task: laplace
  - _self_

exp_name: amber_laplace
_version: 1

trainer:
  max_epochs: 401
idx: amb100

hydra:
  sweeper:
    ablative_params:
      # 1-step
      - algorithm.inference_steps: 1
        task.max_initial_element_volume: 0.00003
        idx: stp100

      # Design ablations
      - algorithm.initial_mesh_handling: exclude  # non-hierarchical
        idx: des100
      - algorithm.sizing_field_damping.damping_factor: 0.0  # no scaling
        idx: des101
      - algorithm.prediction_transform.predict_residual: False  # no baseline/residual prediction
        idx: des102
      - algorithm.prediction_transform.inverse_transform_in_loss: False  # no softplus transformed loss
        idx: des103
      - algorithm.normalizer.normalize_inputs: 0  # no normalization
        algorithm.normalizer.normalize_predictions: 0
        idx: des104
      - algorithm.dataloader.add_strategy: random  # no stratified buffer addition
        idx: des105

      # Sizing field ablations
      - algorithm.sizing_field_interpolation_type: element_weighted_sum  # element-level piecewise-constant field
        idx: sfd100
      - algorithm.sizing_field_interpolation_type: interpolated_vertex  # vertex-level interpolation
        idx: sfd101

      # Sample size/efficiency ablations
      - task.num_data_points.train: 5
        idx: sam100
      - task.num_data_points.train: 100
        idx: sam101
