# Dictionary for all mesh-based metrics that should be computed during training and evaluation.
# Metrics between two meshes are computed between the expert mesh and the reconstructed mesh.
# Solution-based metrics are computed on the reconstructed solution.
element_delta: True  # whether to compute the element-wise difference between the meshes
projected_l2_error: True  # whether to compute the L2 error of the induced mesh sizing fields.
  # The error is calculated on the vertices, and normalized by the reference mesh's sizing field.
  # Also computes a reverse error, i.e., the error of the reference mesh's sizing field on the reconstructed mesh, and
  # the average between the two.
pointcloud:
  midpoint:
    # metrics on the mesh midpoints
    - cd  # whether to compute the chamfer distance between the meshes' midpoints
    - dcd  # density-aware chamfer distance between the meshes' midpoints
    # - ecd  # exponential chamfer distance between the meshes' midpoints
  vertex: ${algorithm.mesh_metrics.pointcloud.midpoint}  # metrics on the mesh vertices